[Mailing] add celery in project
ITA-Dnipro/Dp-Retraining-Python pull request #17
Opened 2022-05-05 11:14 UTC by maklabas

Adds celery service in docker-compose. It's ready to receive tasks.

**References:**
- #16

2022-05-05 12:14 UTC, MaksymShvets approved these changes

2022-05-05 13:59 UTC, evroandrew approved these changes

2022-05-05 14:07 UTC, BorodaUA requested changes

2022-05-05 14:07 UTC, BorodaUA commented on docker-compose.yml
> +        - redis
Do we need a docker service for such thing as running celery inside our api_server container? maybe we should put celery run command in enrypoint.sh?

2022-05-05 14:07 UTC, BorodaUA commented on docker-compose.yml
> +        - "6379:6379"
lets use .env file variables for variables like that.

2022-05-05 14:07 UTC, BorodaUA commented on api_server/celery_app.py
> +    broker="redis://redis/0",
Maybe it is better to put those in some kind of constants, and store it in single place?

2022-05-05 14:07 UTC, BorodaUA commented on docker-compose.yml
> +        - RESULT_BACKEND=redis://redis/1
lets use .env file variables for variables like that.

2022-05-06 05:41 UTC, maklabas commented on docker-compose.yml
> +        - redis
Celery - it's separate docker container and it's independent of our api. I think calculations of celery app should take place in a separate container

2022-05-06 05:57 UTC, maklabas commented on docker-compose.yml
> +        - "6379:6379"
Okay, If it has a reason to use in this case

2022-05-06 05:58 UTC, maklabas commented on api_server/celery_app.py
> +    broker="redis://redis/0",
Yeah, sure. My mistake, I'll change it

2022-05-06 05:59 UTC, maklabas commented on docker-compose.yml
> +        - RESULT_BACKEND=redis://redis/1
Yes, now those variables are being pulled from `.env` file

2022-05-06 13:39 UTC, BorodaUA requested changes

2022-05-06 13:39 UTC, BorodaUA commented on api_server/celery_app.py
> +app.autodiscover_tasks()
Will we have celery jobs? If so, will they be stored in project root? as celery_jobs.py? Maybe we need to create a module for that stuff? Could a module solve that? (not named celery\__init__.py obviously)

2022-05-09 07:17 UTC, BorodaUA approved these changes
Done.

2022-05-09 07:19 UTC, merged